from typing import Final

import inim.prime.native.const

DOMAIN: Final[str] = "inim_prime"


PANEL_LOG_EVENTS_FETCH_LIMIT_DEFAULT: Final[int] = 40
PANEL_LOG_EVENTS_FETCH_LIMIT_TRIGGER: Final[int] = 3
PANEL_LOG_EVENTS_FETCH_LIMIT_MIN: Final[int] = 10
PANEL_LOG_EVENTS_FETCH_LIMIT_MAX: Final[int] = 100


# Native defaults
NATIVE_PORT_DEFAULT: Final[int] = inim.prime.native.const.Panel.DEFAULT_PORT
NATIVE_USE_OUTER_FRAME_DEFAULT: Final[bool] = False
NATIVE_PASSWORD_DEFAULT: Final[str] = inim.prime.native.const.Panel.DEFAULT_PASSWORD
NATIVE_USE_CUSTOM_PIN_DEFAULT: Final[bool] = False
NATIVE_PIN_MAX_CHARACTERS: Final[int] = inim.prime.native.const.Panel.MAX_PIN_CHARACTERS

# Primelan defaults
PRIMELAN_USE_HTTPS_DEFAULT: Final[bool] = True

# --- Defaults (custom per coordinator) ---
ZONES_SCAN_INTERVAL_NATIVE_DEFAULT: Final[int] = 500
PARTITIONS_SCAN_INTERVAL_NATIVE_DEFAULT: Final[int] = 500

ZONES_SCAN_INTERVAL_PRIMELAN_DEFAULT: Final[int] = 5000
PARTITIONS_SCAN_INTERVAL_PRIMELAN_DEFAULT: Final[int] = 10000
GSM_SCAN_INTERVAL_PRIMELAN_DEFAULT: Final[int] = 30000
SYSTEM_FAULTS_SCAN_INTERVAL_PRIMELAN_DEFAULT: Final[int] = 15000
PANEL_LOG_EVENTS_SCAN_INTERVAL_PRIMELAN_DEFAULT: Final[int] = 15000

SCAN_INTERVAL_MIN: Final[int] = 1
SCAN_INTERVAL_MAX: Final[int] = 300000

STORAGE_KEY_LAST_PANEL_EVENT_LOGS = "last_panel_event_logs"

INIM_PRIME_DEVICE_MANUFACTURER = "Inim"
INIM_PRIME_MODEL_ZONE = "Prime Zone"
